pipeline {
    agent any
    stages {
        stage('Git checkout') {
            steps { 
                git 'https://github.com/opedinas/sonar2.git'
            }


        }
        stage('Build') {
            steps {
               sh ''' cd MywebApp && mvn clean package'''
            } 
        }
        stage('test') {
            steps {
                sh 'cd MywebApp && mvn test'
            }
        }
        stage('SonarQube analysis 1') {
            steps {
                sh 'mvn clean package sonar:sonar'
            }
        }
        stage("Quality Gate 1") {
            steps {
                waitForQualityGate abortPipeline: true
            }
        }
        stage('SonarQube analysis 2') {
            steps {
                sh 'gradle sonarqube'
            }
        }
        stage("Quality Gate 2") {
            steps {
                waitForQualityGate abortPipeline: true
            }
        }
        stage ('deploy to tomcat') {
            steps {
                deploy adapters: [tomcat9(credentialsId: '765c974f-80eb-4d22-9e54-493d8887e791', path: '', url: 'http://107.23.9.85:8080/'), tomcat9(path: '', url: '')], contextPath: 'leadgen', war: '**/*.war'
            } 

                
            
        }
    
    }
}   
