pipeline {
    agent any
    stages {
        stage('Git checkout') {
            steps { 
                git 'https://github.com/opedinas/devopyusf.git'
            }


        }
        stage('Build') {
            steps {
               sh 'cd MywebApp && mvn clean package'
            } 
        }
        stage('test') {
            steps {
                sh 'cd MywebApp && mvn test'
            }
        }
        stage ('deploy to tomcat') {
            steps {
                deploy adapters: [tomcat9(credentialsId: '765c974f-80eb-4d22-9e54-493d8887e791', path: '', url: 'http://107.23.9.85:8080/'), tomcat9(path: '', url: '')], contextPath: 'leadgen', war: '**/*.war'
            } 

                
            
        }
    
    }
}   
